apiVersion: v1
kind: Service
metadata:
  name: workspace-service
  labels:
    app.kubernetes.io/name: workspace-service
    app.kubernetes.io/part-of: odysseus
spec:
  selector:
    app.kubernetes.io/name: workspace-service
  ports:
    - name: http
      port: 8081
      targetPort: http
